# Generated by Django 3.1.1 on 2020-10-03 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0003_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
