# Generated by Django 3.1.1 on 2020-10-04 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0004_delete_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cour_id', models.CharField(max_length=40)),
                ('cour_cate', models.CharField(max_length=5)),
            ],
        ),
    ]
